import React, { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Sparkles, Send, Loader2, Mail, Edit } from 'lucide-react';
import { toast } from 'sonner';

export default function ClientCommunicationPanel({ client, contacts }) {
  const queryClient = useQueryClient();
  const [mode, setMode] = useState('request'); // 'request' or 'preview'
  const [userRequest, setUserRequest] = useState('');
  const [draftedSubject, setDraftedSubject] = useState('');
  const [draftedBody, setDraftedBody] = useState('');
  const [selectedContact, setSelectedContact] = useState('');
  const [aiPrompt, setAiPrompt] = useState('');
  const [aiResponseRaw, setAiResponseRaw] = useState('');

  const draftMutation = useMutation({
    mutationFn: (data) => base44.functions.invoke('aiDraftCommunication', data),
    onSuccess: (response) => {
      const { drafted_communication } = response.data;
      setDraftedSubject(drafted_communication.subject);
      setDraftedBody(drafted_communication.body);
      setAiPrompt(userRequest);
      setAiResponseRaw(JSON.stringify(drafted_communication));
      setMode('preview');
      toast.success('Draft generated by AI');
    },
    onError: (error) => {
      toast.error(error.message || 'Failed to generate draft');
    }
  });

  const sendMutation = useMutation({
    mutationFn: (data) => base44.functions.invoke('sendClientCommunication', data),
    onSuccess: () => {
      toast.success('Communication sent successfully');
      queryClient.invalidateQueries({ queryKey: ['client-communications', client.id] });
      // Reset form
      setMode('request');
      setUserRequest('');
      setDraftedSubject('');
      setDraftedBody('');
      setSelectedContact('');
    },
    onError: (error) => {
      toast.error(error.message || 'Failed to send communication');
    }
  });

  const handleDraft = () => {
    if (!userRequest.trim()) {
      toast.error('Please enter a request for the AI');
      return;
    }

    draftMutation.mutate({
      client_id: client.id,
      user_request_text: userRequest,
      communication_type: 'email'
    });
  };

  const handleSend = () => {
    if (!selectedContact) {
      toast.error('Please select a recipient');
      return;
    }

    const contact = contacts.find(c => c.id === selectedContact);
    
    sendMutation.mutate({
      client_id: client.id,
      recipient_email: contact.email,
      subject: draftedSubject,
      body: draftedBody,
      communication_type: 'email',
      is_ai_drafted: true,
      ai_prompt: aiPrompt,
      ai_response_raw: aiResponseRaw,
      contact_id: contact.id
    });
  };

  return (
    <div className="neumorphic-raised rounded-xl p-6">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#BD00FF] to-[#9000cc] flex items-center justify-center">
          <Sparkles className="w-5 h-5 text-white" />
        </div>
        <div>
          <h3 className="font-medium">AI Communication Assistant</h3>
          <p className="text-xs text-[#A0AEC0]">Draft personalized emails with AI</p>
        </div>
      </div>

      {mode === 'request' ? (
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-[#A0AEC0] mb-2">
              What would you like to communicate?
            </label>
            <Textarea
              value={userRequest}
              onChange={(e) => setUserRequest(e.target.value)}
              placeholder="E.g., 'Draft an email to thank them for the meeting and confirm next steps for the Q1 review'"
              className="bg-[#1A1B1E] border-[#2C2E33] h-32"
            />
          </div>

          <Button
            onClick={handleDraft}
            disabled={!userRequest.trim() || draftMutation.isPending}
            className="w-full bg-gradient-to-r from-[#BD00FF] to-[#9000cc] text-white"
          >
            {draftMutation.isPending ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Drafting...
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4 mr-2" />
                Generate Draft
              </>
            )}
          </Button>
        </div>
      ) : (
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-[#A0AEC0] mb-2">Recipient</label>
            <Select value={selectedContact} onValueChange={setSelectedContact}>
              <SelectTrigger className="bg-[#1A1B1E] border-[#2C2E33]">
                <SelectValue placeholder="Select contact" />
              </SelectTrigger>
              <SelectContent className="bg-[#2C2E33] border-[#3a3d44]">
                {contacts.map(contact => (
                  <SelectItem key={contact.id} value={contact.id}>
                    {contact.first_name} {contact.last_name} ({contact.email})
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div>
            <label className="block text-sm font-medium text-[#A0AEC0] mb-2">Subject</label>
            <Input
              value={draftedSubject}
              onChange={(e) => setDraftedSubject(e.target.value)}
              className="bg-[#1A1B1E] border-[#2C2E33]"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-[#A0AEC0] mb-2">Message</label>
            <Textarea
              value={draftedBody}
              onChange={(e) => setDraftedBody(e.target.value)}
              className="bg-[#1A1B1E] border-[#2C2E33] h-64"
            />
          </div>

          <div className="flex gap-3">
            <Button
              variant="outline"
              onClick={() => setMode('request')}
              className="flex-1 border-[#2C2E33]"
            >
              <Edit className="w-4 h-4 mr-2" />
              Redraft
            </Button>
            <Button
              onClick={handleSend}
              disabled={!selectedContact || sendMutation.isPending}
              className="flex-1 bg-gradient-to-r from-[#00E5FF] to-[#0099ff] text-[#121212]"
            >
              {sendMutation.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Sending...
                </>
              ) : (
                <>
                  <Send className="w-4 h-4 mr-2" />
                  Send Email
                </>
              )}
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}