/**
 * System block type definitions — seeded per-org on first provision.
 * These types are `is_system = true` and cannot be deleted by users.
 */
export const SYSTEM_BLOCK_TYPES = [
  {
    type_name: 'client',
    display_name: 'Client',
    description: 'A client entity — company or individual your firm services.',
    icon: 'building',
    color: 'blue',
    field_schema: {
      type: 'object',
      'x-field-groups': [
        { id: 'identification', label: 'Identification', order: 1 },
        { id: 'compliance', label: 'Compliance', order: 2 },
      ],
      properties: {
        jurisdiction: {
          type: 'string',
          enum: ['AU', 'US', 'GB', 'SG', 'HK', 'NZ', 'JP', 'DE', 'FR', 'CA'],
          description: 'Primary jurisdiction (ISO 3166-1 alpha-2)',
          'x-field-group': 'compliance',
          'x-display-order': 1,
        },
        entity_type: {
          type: 'string',
          enum: ['individual', 'company', 'trust', 'partnership', 'government'],
          description: 'Legal entity classification',
          'x-field-group': 'identification',
          'x-display-order': 1,
        },
        incorporation_date: {
          type: 'string',
          description: 'Date of incorporation (YYYY-MM-DD)',
          'x-field-group': 'identification',
          'x-display-order': 2,
        },
      },
    },
  },
  {
    type_name: 'deal',
    display_name: 'Deal',
    description: 'A business deal or opportunity being tracked.',
    icon: 'handshake',
    color: 'green',
    field_schema: {
      type: 'object',
      'x-field-groups': [
        { id: 'pipeline', label: 'Pipeline', order: 1 },
        { id: 'financials', label: 'Financials', order: 2 },
      ],
      properties: {
        deal_value: {
          type: 'number',
          minimum: 0,
          description: 'Deal value in base currency',
          'x-field-group': 'financials',
          'x-display-order': 1,
        },
        stage: {
          type: 'string',
          enum: ['prospect', 'qualified', 'proposal', 'negotiation', 'closed_won', 'closed_lost'],
          description: 'Current deal stage',
          'x-field-group': 'pipeline',
          'x-display-order': 1,
        },
        expected_close: {
          type: 'string',
          description: 'Expected close date (YYYY-MM-DD)',
          'x-field-group': 'pipeline',
          'x-display-order': 2,
        },
      },
    },
  },
  {
    type_name: 'project',
    display_name: 'Project',
    description: 'A project or engagement being delivered.',
    icon: 'folder',
    color: 'purple',
    field_schema: {
      type: 'object',
      properties: {
        status: {
          type: 'string',
          enum: ['planning', 'in_progress', 'on_hold', 'completed', 'cancelled'],
          description: 'Project status',
        },
        priority: {
          type: 'string',
          enum: ['low', 'medium', 'high', 'critical'],
          description: 'Priority level',
        },
        due_date: {
          type: 'string',
          description: 'Due date (YYYY-MM-DD)',
        },
      },
    },
  },
  {
    type_name: 'contact',
    display_name: 'Contact',
    description: 'A person associated with a client or deal.',
    icon: 'user',
    color: 'gray',
    field_schema: {
      type: 'object',
      'x-field-groups': [
        { id: 'contact_info', label: 'Contact Information', order: 1 },
        { id: 'preferences', label: 'Preferences', order: 2 },
        { id: 'notes', label: 'Notes', order: 3 },
      ],
      properties: {
        role: {
          type: 'string',
          description: 'Role or title',
          'x-field-group': 'contact_info',
          'x-display-order': 1,
        },
        email: {
          type: 'string',
          format: 'email',
          description: 'Email address',
          'x-field-group': 'contact_info',
          'x-display-order': 2,
        },
        phone: {
          type: 'string',
          description: 'Phone number',
          'x-field-group': 'contact_info',
          'x-display-order': 3,
        },
        timezone: {
          type: 'string',
          maxLength: 50,
          description: 'IANA timezone (e.g. Australia/Sydney)',
          'x-field-group': 'contact_info',
          'x-display-order': 4,
        },
        response_time_sla: {
          type: 'string',
          enum: ['1h', '4h', '8h', '24h', '48h'],
          description: 'Expected response time SLA',
          'x-field-group': 'preferences',
          'x-display-order': 1,
        },
        communication_preference: {
          type: 'string',
          enum: ['email', 'phone', 'slack', 'teams'],
          description: 'Preferred communication channel',
          'x-field-group': 'preferences',
          'x-display-order': 2,
        },
        preferred_contact_method: {
          type: 'string',
          enum: ['email', 'phone', 'in_person', 'video_call'],
          description: 'Preferred method of contact',
          'x-field-group': 'preferences',
          'x-display-order': 3,
        },
        signature_template: {
          type: 'string',
          maxLength: 2000,
          description: 'Email signature template (HTML or markdown)',
          'x-field-group': 'preferences',
          'x-display-order': 4,
        },
        notes: {
          type: 'string',
          maxLength: 5000,
          description: 'Free-form notes about this contact',
          'x-field-group': 'notes',
          'x-display-order': 1,
        },
      },
    },
  },
  {
    type_name: 'contract',
    display_name: 'Contract',
    description: 'A legal contract or agreement.',
    icon: 'file-text',
    color: 'amber',
    field_schema: {
      type: 'object',
      properties: {
        contract_type: {
          type: 'string',
          enum: ['service_agreement', 'nda', 'sow', 'msa', 'amendment', 'addendum'],
          description: 'Type of contract',
        },
        effective_date: {
          type: 'string',
          description: 'Effective date (YYYY-MM-DD)',
        },
        expiry_date: {
          type: 'string',
          description: 'Expiry date (YYYY-MM-DD)',
        },
        value: {
          type: 'number',
          minimum: 0,
          description: 'Contract value in base currency',
        },
      },
    },
  },
  {
    type_name: 'workflow_template',
    display_name: 'Workflow Template',
    description: 'A reusable workflow definition with triggers, steps, and conditions.',
    icon: 'git-branch',
    color: 'indigo',
    field_schema: {
      type: 'object',
      properties: {
        applies_to_type: { type: 'string', description: 'Block type this workflow applies to' },
        trigger: { type: 'object', description: 'Trigger configuration' },
        steps: { type: 'array', description: 'Ordered list of workflow steps' },
        description: { type: 'string', description: 'Workflow description' },
      },
      required: ['applies_to_type', 'trigger', 'steps'],
    },
  },
  {
    type_name: 'workflow_instance',
    display_name: 'Workflow Instance',
    description: 'A running instance of a workflow template.',
    icon: 'play',
    color: 'cyan',
    field_schema: {
      type: 'object',
      properties: {
        template_id: { type: 'string', description: 'ID of the workflow template block' },
        source_block_id: { type: 'string', description: 'ID of the block that triggered this workflow' },
        applies_to_type: { type: 'string', description: 'Block type this workflow processes' },
        status: {
          type: 'string',
          enum: ['pending', 'running', 'done', 'failed'],
          description: 'Current execution status',
        },
        current_step_index: { type: 'number', description: 'Index of the current step being executed' },
        step_results: { type: 'array', description: 'Results from completed steps' },
        started_at: { type: 'string', description: 'When execution started' },
        completed_at: { type: 'string', description: 'When execution completed' },
      },
      required: ['template_id', 'source_block_id', 'status'],
    },
  },
  {
    type_name: 'task_queue_item',
    display_name: 'Task',
    description: 'A pending task created by a workflow step, assigned to a human or agent.',
    icon: 'check-square',
    color: 'orange',
    field_schema: {
      type: 'object',
      properties: {
        workflow_instance_id: { type: 'string', description: 'ID of the parent workflow instance' },
        step_name: { type: 'string', description: 'Name of the workflow step that created this task' },
        assigned_to: { type: 'string', description: 'User ID of the assignee' },
        claimed_at: { type: 'string', description: 'When the task was claimed' },
        completed_at: { type: 'string', description: 'When the task was completed' },
        status: {
          type: 'string',
          enum: ['open', 'claimed', 'completed'],
          description: 'Task status',
        },
        instructions: { type: 'string', description: 'Instructions for the task assignee' },
        ai_recommendation: { type: 'object', description: 'AI-suggested action/output for this task' },
        confidence_score: { type: 'number', minimum: 0, maximum: 1, description: 'AI confidence in its recommendation (0.0-1.0)' },
        routing_decision: { type: 'string', enum: ['human', 'agent', 'approval_chain'], description: 'How this task was routed' },
        routing_reason: { type: 'string', description: 'Human-readable explanation of the routing decision' },
        input_data: { type: 'object', description: 'Structured input context (block data, previous step output)' },
        expected_output_schema: { type: 'object', description: 'JSON schema describing expected output' },
        actual_output: { type: 'object', description: 'Actual output produced by the handler' },
        completed_by: { type: 'string', description: 'Clerk user ID or agent identifier' },
        decision: { type: 'string', enum: ['approved', 'rejected', 'modified'], description: 'Human decision on AI recommendation' },
      },
      required: ['workflow_instance_id', 'step_name', 'status'],
    },
  },
  {
    type_name: 'document_template',
    display_name: 'Document Template',
    description: 'A reusable document template for generating contracts, proposals, or reports.',
    icon: 'file-text',
    color: 'amber',
    field_schema: {
      type: 'object',
      properties: {
        template_content: {
          type: 'string',
          description: 'Template body in HTML or Markdown with {{variable}} placeholders',
        },
        variables: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              name: { type: 'string', description: 'Variable name (e.g., block.name)' },
              type: { type: 'string', enum: ['string', 'number', 'date', 'currency'], description: 'Data type' },
              required: { type: 'boolean', description: 'Whether this variable must be provided' },
            },
            required: ['name', 'type'],
          },
          description: 'Variables used in this template',
        },
        output_format: {
          type: 'string',
          enum: ['pdf', 'html', 'markdown'],
          description: 'Default output format',
        },
        category: {
          type: 'string',
          enum: ['contract', 'proposal', 'nda', 'report', 'letter', 'invoice', 'other'],
          description: 'Template category',
        },
        reference_file_path: {
          type: 'string',
          description: 'Supabase Storage path to the uploaded reference document',
        },
        reference_file_name: {
          type: 'string',
          description: 'Original filename of the uploaded reference document',
        },
        reference_mime_type: {
          type: 'string',
          description: 'MIME type of the uploaded reference document',
        },
        structure_description: {
          type: 'string',
          description: 'AI-extracted description of the reference document structure and layout',
        },
      },
      required: [],
    },
  },
  {
    type_name: 'brand_kit',
    display_name: 'Brand Kit',
    description: 'Organisation brand identity — logo, colours, fonts, and styling for documents.',
    icon: 'palette',
    color: 'rose',
    field_schema: {
      type: 'object',
      properties: {
        logo_url: { type: 'string', description: 'URL to organisation logo' },
        primary_color: { type: 'string', description: 'Primary brand colour (hex, e.g., #1a2b3c)' },
        secondary_color: { type: 'string', description: 'Secondary brand colour (hex)' },
        font_family: { type: 'string', description: 'Font family for documents (e.g., Inter, sans-serif)' },
        header_style: {
          type: 'object',
          properties: {
            background_color: { type: 'string', description: 'Header background colour' },
            text_color: { type: 'string', description: 'Header text colour' },
            show_logo: { type: 'boolean', description: 'Whether to show logo in header' },
          },
          description: 'Document header styling',
        },
        footer_content: { type: 'string', description: 'Footer text for documents (HTML allowed)' },
        company_name: { type: 'string', description: 'Company display name' },
        tagline: { type: 'string', description: 'Company tagline or motto' },
      },
      required: ['company_name', 'primary_color'],
    },
  },
  {
    type_name: 'solution',
    display_name: 'Solution',
    description: 'A packaged solution combining products and services for a client need.',
    icon: 'lightbulb',
    color: 'blue',
    field_schema: {
      type: 'object',
      properties: {
        status: {
          type: 'string',
          enum: ['draft', 'active', 'deprecated', 'archived'],
          description: 'Solution lifecycle status',
        },
        category: {
          type: 'string',
          description: 'Solution category (e.g., compliance, advisory)',
        },
        target_industry: {
          type: 'string',
          description: 'Primary target industry vertical',
        },
        key_features: {
          type: 'array',
          items: { type: 'string' },
          description: 'Key features or capabilities',
        },
        pricing_model: {
          type: 'string',
          enum: ['fixed', 'hourly', 'retainer', 'subscription', 'hybrid'],
          description: 'Pricing model for this solution',
        },
        base_price: {
          type: 'number',
          minimum: 0,
          description: 'Base price per unit or period',
        },
        quantity: {
          type: 'number',
          minimum: 0,
          description: 'Number of units or seats',
        },
        deal_value: {
          type: 'number',
          minimum: 0,
          description: 'Total deal value (override or base_price × quantity)',
        },
        recurring: {
          type: 'boolean',
          description: 'Whether this is a recurring charge',
        },
        billing_period: {
          type: 'string',
          enum: ['monthly', 'quarterly', 'annually'],
          description: 'Billing frequency for recurring solutions',
        },
        currency: {
          type: 'string',
          maxLength: 3,
          description: 'ISO 4217 currency code (e.g., AUD, USD)',
        },
        product_refs: {
          type: 'array',
          items: { type: 'string' },
          description: 'Block IDs of included products',
        },
        service_refs: {
          type: 'array',
          items: { type: 'string' },
          description: 'Block IDs of included services',
        },
      },
    },
  },
  {
    type_name: 'product',
    display_name: 'Product',
    description: 'A tangible or digital product offered by the organisation.',
    icon: 'package',
    color: 'green',
    field_schema: {
      type: 'object',
      properties: {
        version: {
          type: 'string',
          description: 'Product version or edition',
        },
        status: {
          type: 'string',
          enum: ['draft', 'active', 'discontinued', 'archived'],
          description: 'Product lifecycle status',
        },
        sku: {
          type: 'string',
          description: 'Stock keeping unit or product code',
        },
        category: {
          type: 'string',
          description: 'Product category',
        },
        unit_price: {
          type: 'number',
          minimum: 0,
          description: 'Unit price in base currency',
        },
        currency: {
          type: 'string',
          maxLength: 3,
          description: 'ISO 4217 currency code (e.g., AUD, USD)',
        },
        default_price: {
          type: 'number',
          minimum: 0,
          description: 'Default list price (before discounts or tiers)',
        },
        pricing_tiers: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              label: { type: 'string', description: 'Tier name (e.g., Starter, Pro, Enterprise)' },
              min_quantity: { type: 'number', description: 'Minimum quantity for this tier' },
              unit_price: { type: 'number', description: 'Price per unit at this tier' },
            },
          },
          description: 'Volume-based pricing tiers',
        },
        availability_date: {
          type: 'string',
          description: 'Available from date (YYYY-MM-DD)',
        },
      },
    },
  },
  {
    type_name: 'service',
    display_name: 'Service',
    description: 'A professional service offered by the organisation.',
    icon: 'wrench',
    color: 'purple',
    field_schema: {
      type: 'object',
      properties: {
        service_type: {
          type: 'string',
          enum: ['consulting', 'advisory', 'managed', 'implementation', 'support', 'training'],
          description: 'Type of service',
        },
        delivery_model: {
          type: 'string',
          enum: ['onsite', 'remote', 'hybrid'],
          description: 'Service delivery model',
        },
        sla_tier: {
          type: 'string',
          enum: ['standard', 'premium', 'enterprise'],
          description: 'Service level agreement tier',
        },
        hourly_rate: {
          type: 'number',
          minimum: 0,
          description: 'Hourly rate in base currency',
        },
        currency: {
          type: 'string',
          maxLength: 3,
          description: 'ISO 4217 currency code (e.g., AUD, USD)',
        },
        default_rate: {
          type: 'number',
          minimum: 0,
          description: 'Default rate (before client-specific adjustments)',
        },
        pricing_tiers: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              label: { type: 'string', description: 'Tier name (e.g., Standard, Premium, Enterprise)' },
              hours_included: { type: 'number', description: 'Hours included in this tier' },
              rate: { type: 'number', description: 'Hourly rate at this tier' },
              retainer_fee: { type: 'number', description: 'Fixed monthly retainer fee for this tier' },
            },
          },
          description: 'Service pricing tiers',
        },
        engagement_type: {
          type: 'string',
          enum: ['project', 'retainer', 'ad_hoc', 'subscription'],
          description: 'Engagement billing model',
        },
      },
    },
  },
  {
    type_name: 'team_member',
    display_name: 'Team Member',
    description: 'A person who is part of the organisation team.',
    icon: 'user-circle',
    color: 'orange',
    field_schema: {
      type: 'object',
      'x-field-groups': [
        { id: 'profile', label: 'Profile', order: 1 },
        { id: 'organisation', label: 'Organisation', order: 2 },
        { id: 'system', label: 'System', order: 3 },
      ],
      properties: {
        email: {
          type: 'string',
          format: 'email',
          description: 'Work email address',
          'x-field-group': 'profile',
          'x-display-order': 1,
        },
        role_title: {
          type: 'string',
          description: 'Job title or role name',
          'x-field-group': 'profile',
          'x-display-order': 2,
        },
        start_date: {
          type: 'string',
          description: 'Start date (YYYY-MM-DD)',
          'x-field-group': 'profile',
          'x-display-order': 3,
        },
        status: {
          type: 'string',
          enum: ['active', 'on_leave', 'offboarding', 'inactive'],
          description: 'Employment status',
          'x-field-group': 'profile',
          'x-display-order': 4,
        },
        department: {
          type: 'string',
          description: 'Department or division',
          'x-field-group': 'organisation',
          'x-display-order': 1,
        },
        reporting_to: {
          type: 'string',
          description: 'Block ID of the manager (team_member block)',
          'x-field-group': 'organisation',
          'x-display-order': 2,
        },
        clerk_user_id: {
          type: 'string',
          description: 'Clerk user ID for auth linkage',
          'x-field-group': 'system',
          'x-display-order': 1,
        },
      },
    },
  },
  {
    type_name: 'policy',
    display_name: 'Policy',
    description: 'An organisational policy governing routing, compliance, or operational rules.',
    icon: 'shield',
    color: 'red',
    field_schema: {
      type: 'object',
      'x-field-groups': [
        { id: 'policy_details', label: 'Policy Details', order: 1 },
        { id: 'routing_config', label: 'Routing Configuration', order: 2 },
        { id: 'escalation', label: 'Escalation', order: 3 },
      ],
      properties: {
        policy_type: {
          type: 'string',
          enum: ['routing', 'compliance', 'operational', 'security', 'approval'],
          description: 'Type of policy',
          'x-field-group': 'policy_details',
          'x-display-order': 1,
        },
        effective_date: {
          type: 'string',
          description: 'Effective from date (YYYY-MM-DD)',
          'x-field-group': 'policy_details',
          'x-display-order': 2,
        },
        review_date: {
          type: 'string',
          description: 'Next review date (YYYY-MM-DD)',
          'x-field-group': 'policy_details',
          'x-display-order': 3,
        },
        status: {
          type: 'string',
          enum: ['draft', 'active', 'under_review', 'superseded', 'archived'],
          description: 'Policy status',
          'x-field-group': 'policy_details',
          'x-display-order': 4,
        },
        approval_required: {
          type: 'boolean',
          description: 'Whether actions under this policy require approval',
          'x-field-group': 'policy_details',
          'x-display-order': 5,
        },
        jurisdiction: {
          type: 'string',
          enum: ['AU', 'US', 'GB', 'SG', 'HK', 'NZ', 'JP', 'DE', 'FR', 'CA', 'global'],
          description: 'Applicable jurisdiction (ISO 3166-1 alpha-2 or global)',
          'x-field-group': 'policy_details',
          'x-display-order': 6,
        },
        routing_mode: {
          type: 'string',
          enum: ['human_only', 'ai_only', 'hybrid', 'escalation_chain'],
          description: 'Default routing mode for this policy',
          'x-field-group': 'routing_config',
          'x-display-order': 1,
        },
        confidence_threshold: {
          type: 'number',
          minimum: 0,
          maximum: 1,
          description: 'Minimum AI confidence score (0.0-1.0) to auto-approve a routing decision',
          'x-field-group': 'routing_config',
          'x-display-order': 2,
        },
        risk_routing_map: {
          type: 'object',
          additionalProperties: {
            type: 'object',
            properties: {
              mode: { type: 'string', enum: ['human_only', 'ai_only', 'hybrid', 'escalation_chain'] },
              threshold: { type: 'number', minimum: 0, maximum: 1 },
            },
            required: ['mode', 'threshold'],
          },
          description: 'Maps risk level names to routing decisions',
          'x-field-group': 'routing_config',
          'x-display-order': 3,
        },
        approval_chain: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              role: { type: 'string', description: 'Role name or permission required' },
              order: { type: 'number', description: 'Approval order (1 = first)' },
              required: { type: 'boolean', description: 'Whether this approver is mandatory' },
            },
            required: ['role', 'order', 'required'],
          },
          description: 'Ordered list of approvers for escalation_chain routing',
          'x-field-group': 'escalation',
          'x-display-order': 1,
        },
        fallback_routing: {
          type: 'string',
          enum: ['human_only'],
          description: 'Fallback routing mode when no policy rule matches',
          'x-field-group': 'escalation',
          'x-display-order': 2,
        },
        max_ai_attempts: {
          type: 'number',
          minimum: 1,
          maximum: 10,
          description: 'Maximum AI retry attempts before escalating to human (default 3)',
          'x-field-group': 'escalation',
          'x-display-order': 3,
        },
      },
    },
  },
  {
    type_name: 'swot_analysis',
    display_name: 'SWOT Analysis',
    description: 'A strategic analysis of strengths, weaknesses, opportunities, and threats.',
    icon: 'grid-2x2',
    color: 'amber',
    field_schema: {
      type: 'object',
      'x-field-groups': [
        { id: 'internal', label: 'Internal Factors', order: 1 },
        { id: 'external', label: 'External Factors', order: 2 },
        { id: 'context', label: 'Context', order: 3 },
      ],
      properties: {
        strengths: {
          type: 'array',
          items: { type: 'string' },
          description: 'Internal strengths and capabilities',
          'x-field-group': 'internal',
          'x-display-order': 1,
        },
        weaknesses: {
          type: 'array',
          items: { type: 'string' },
          description: 'Internal weaknesses and limitations',
          'x-field-group': 'internal',
          'x-display-order': 2,
        },
        opportunities: {
          type: 'array',
          items: { type: 'string' },
          description: 'External opportunities to pursue',
          'x-field-group': 'external',
          'x-display-order': 1,
        },
        threats: {
          type: 'array',
          items: { type: 'string' },
          description: 'External threats and risks',
          'x-field-group': 'external',
          'x-display-order': 2,
        },
        analysis_date: {
          type: 'string',
          description: 'Date of analysis (YYYY-MM-DD)',
          'x-field-group': 'context',
          'x-display-order': 1,
        },
        context_block_id: {
          type: 'string',
          description: 'Optional reference to the client or org block being analysed',
          'x-field-group': 'context',
          'x-display-order': 2,
        },
        ai_generated: {
          type: 'boolean',
          description: 'Whether this analysis was AI-generated',
          'x-field-group': 'context',
          'x-display-order': 3,
        },
      },
    },
  },
  {
    type_name: 'value_proposition',
    display_name: 'Value Proposition',
    description: 'A statement of the unique value offered to a target audience.',
    icon: 'target',
    color: 'emerald',
    field_schema: {
      type: 'object',
      'x-field-groups': [
        { id: 'proposition', label: 'Proposition', order: 1 },
        { id: 'evidence', label: 'Evidence', order: 2 },
      ],
      properties: {
        target_audience: {
          type: 'string',
          description: 'Who this value proposition is for',
          'x-field-group': 'proposition',
          'x-display-order': 1,
        },
        unique_value: {
          type: 'string',
          description: 'The unique value or benefit delivered',
          'x-field-group': 'proposition',
          'x-display-order': 2,
        },
        competitive_advantage: {
          type: 'string',
          description: 'What differentiates this from competitors',
          'x-field-group': 'proposition',
          'x-display-order': 3,
        },
        positioning_statement: {
          type: 'string',
          description: 'Full positioning statement',
          'x-field-group': 'proposition',
          'x-display-order': 4,
        },
        proof_points: {
          type: 'array',
          items: { type: 'string' },
          description: 'Evidence or proof points supporting this proposition',
          'x-field-group': 'evidence',
          'x-display-order': 1,
        },
        status: {
          type: 'string',
          enum: ['draft', 'active', 'archived'],
          description: 'Proposition lifecycle status',
          'x-field-group': 'evidence',
          'x-display-order': 2,
        },
      },
    },
  },
] as const
